Global:
  debug: false
  use_gpu: true
  epoch_num: 200
  log_smooth_window: 0
  print_batch_step: 1000
  save_model_dir: ./trials/newrec/hardneg_allaugs
  save_epoch_step: 200
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/en_PP-OCRv3_rec_train/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: 25
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3_en.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.00014
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride:
    - 1
    - 2
    last_pool_type: avg
  Head:
    name: MultiHead
    head_list:
    - CTCHead:
        Neck:
          name: svtr
          dims: 64
          depth: 2
          hidden_dims: 120
          use_guide: true
        Head:
          fc_decay: 1.0e-05
    - SARHead:
        enc_dim: 512
        max_text_length: 25
Loss:
  name: MultiLoss
  loss_config_list:
  - CTCLoss: null
  - SARLoss: null
CTCLoss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./aug_train/
    ext_op_transform_idx: 1
    label_file_list:
    - ./aug_train/train_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.05
        ext_data_num: 3
        image_shape:
        - 48
        - 320
        - 3
        max_text_length: 100
    - RecAug:
        tia_prob: 0.4
        crop_prob: 0.4
        reverse_prob: 0.4
        noise_prob: 0.4
        jitter_prob: 0.4
        blur_prob: 0.4
        hsv_aug_prob: 0.4
        use_imgaug: 1
        affine_scale_diff: 0.09
        affine_translate_percent: 0.1
        affine_rotation: 20
        affine_shear: 20
        affine_prob: 0.3
        channelshuffle_prob: 0.28
        add_amount: 50
        add_gaussian_amount: 0.27
        multiply_amount: 0.13
        dropout_percent: 0.05
        c_dropout_percent: 0.05
        c_dropout_size_percent: 0.05
        invert_prob: 0.5
        jpeg_compression: 0.3
        gaussian_sigma: 3
        motionblur_kernel: 3
        hs_multiplier: 0.05
        saturation_remover: 0.33
        color_temp_shift: 5000
        contrast_gamma: 0.5
        cloud_snow_prob: 0.01
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 96
    drop_last: true
    num_workers: 8
Alt:
  dataset:
    name: SimpleDataSet
    data_dir: ./aug_train/
    ext_op_transform_idx: 1
    label_file_list:
    - ./aug_train/alt_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.05
        ext_data_num: 3
        image_shape:
        - 48
        - 320
        - 3
        max_text_length: 100
    - RecAug:
        tia_prob: 0.3
        crop_prob: 0.3
        reverse_prob: 0.3
        noise_prob: 0.3
        jitter_prob: 0.3
        blur_prob: 0.3
        hsv_aug_prob: 0.3
        use_imgaug: 1
        affine_scale_diff: 0.09
        affine_translate_percent: 0.1
        affine_rotation: 20
        affine_shear: 20
        affine_prob: 0.3
        channelshuffle_prob: 0.28
        add_amount: 50
        add_gaussian_amount: 0.27
        multiply_amount: 0.13
        dropout_percent: 0.05
        c_dropout_percent: 0.05
        c_dropout_size_percent: 0.05
        invert_prob: 0.5
        jpeg_compression: 0.3
        gaussian_sigma: 3
        motionblur_kernel: 3
        hs_multiplier: 0.05
        saturation_remover: 0.33
        color_temp_shift: 5000
        contrast_gamma: 0.5
        cloud_snow_prob: 0.01
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 96
    drop_last: true
    num_workers: 8
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./aug_train/
    label_file_list:
    - ./aug_train/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 8
Test:
  dataset:
    name: SimpleDataSet
    data_dir: ./aug_train/test_imgs/
    label_file_list:
    - ./aug_train/test_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 8
profiler_options: null
