Global:
  debug: false
  use_gpu: true
  epoch_num: 400
  log_smooth_window: 0
  print_batch_step: 1000
  save_model_dir: ./rec_train/feb9_CLEANEDDATA_nodefualt_maxmaximgaug_reccon
  save_epoch_step: 250
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: true
  pretrained_model: ./pretrain_models/en_PP-OCRv3_rec_train/best_accuracy
  # pretrained_model: ./trials/newrec/hardneg_allaugs_evenlesspower_newset/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: ppocr/utils/en_dict.txt
  max_text_length: 100
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: ./output/rec/predicts_ppocrv3_en.txt
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0002
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 1.0e-05
Architecture:
  model_type: rec
  algorithm: SVTR
  Transform: null
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride:
    - 1
    - 2
    last_pool_type: avg
  Head:
    name: MultiHead
    head_list:
    - CTCHead:
        Neck:
          name: svtr
          dims: 64
          depth: 2
          hidden_dims: 120
          use_guide: true
        Head:
          fc_decay: 1.0e-05
    - SARHead:
        enc_dim: 512
        max_text_length: 25
Loss:
  name: MultiLoss
  loss_config_list:
  - CTCLoss: null
  - SARLoss: null
CTCLoss:
  name: CTCLoss
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: false
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/train_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.25
        ext_data_num: 4
        image_shape:
        - 48
        - 320
        - 3
        max_text_length: 100
    - RecAug:
        tia_prob: 0
        crop_prob: 0
        reverse_prob: 0
        noise_prob: 0
        jitter_prob: 0
        blur_prob: 0
        hsv_aug_prob: 0
        use_imgaug: 1
        affine_scale_diff: 0.3
        affine_translate_percent: 03
        affine_rotation: 30
        affine_shear: 30
        affine_prob: 0.5
        channelshuffle_prob: 1.0
        add_amount: 255
        add_gaussian_amount: 1.0
        multiply_amount: 1.0
        dropout_percent: 0.5
        c_dropout_percent: 0.5
        c_dropout_size_percent: 0.1
        invert_prob: 0.3
        jpeg_compression: 0.9
        gaussian_sigma: 9
        motionblur_kernel: 9
        hs_multiplier: 1.0
        saturation_remover: 1.0
        color_temp_shift: 30000
        contrast_gamma: 0.5
        cloud_snow_prob: 0.05
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    drop_last: true
    batch_size_per_card: 256
    num_workers: 6
Alt:
  dataset:
    name: SimpleDataSet 
    data_dir: ./train_data/
    ext_op_transform_idx: 1
    label_file_list:
    - ./train_data/alt_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.25
        ext_data_num: 4
        image_shape:
        - 48
        - 320
        - 3
        max_text_length: 100
    - RecAug:
        tia_prob: 0
        crop_prob: 0
        reverse_prob: 0
        noise_prob: 0
        jitter_prob: 0
        blur_prob: 0
        hsv_aug_prob: 0
        use_imgaug: 1
        affine_scale_diff: 0.3
        affine_translate_percent: 03
        affine_rotation: 30
        affine_shear: 30
        affine_prob: 0.5
        channelshuffle_prob: 1.0
        add_amount: 255
        add_gaussian_amount: 1.0
        multiply_amount: 1.0
        dropout_percent: 0.5
        c_dropout_percent: 0.5
        c_dropout_size_percent: 0.1
        invert_prob: 0.3
        jpeg_compression: 0.9
        gaussian_sigma: 9
        motionblur_kernel: 9
        hs_multiplier: 1.0
        saturation_remover: 1.0
        color_temp_shift: 30000
        contrast_gamma: 0.5
        cloud_snow_prob: 0.05
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    drop_last: true
    batch_size_per_card: 256
    num_workers: 6
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/
    label_file_list:
    - ./train_data/val_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    drop_last: true
    batch_size_per_card: 128
    num_workers: 6
Test:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/test_imgs/
    label_file_list:
    - ./train_data/test_list.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode: null
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 320
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 256
    num_workers: 6
